if: tag IS NOT present
os: windows
language: cpp

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco upgrade --no-progress -y msys2
        taskkill //IM gpg-agent.exe //F
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

install:
  - choco install openssl -y --x86
  - choco install jdk8 -y
  - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
  - choco install msys2 -y

script:
  - mkdir ~/MultiMC && cd ~/MultiMC
  - mkdir build
  - mkdir install
  - git clone --recursive https://github.com/Sebastian-byte/MultiMC5-Cracked.git src
  - cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=.\install
  - mingw32-make -j3
  - mingw32-make install
  - ls -lAh ~/MultiMC/ && ls -lAh ~/MultiMC/build && ls -lAh ~/MultiMC/install && ls -lAh ~/MultiMC/src && ls -lAh ~/MultiMC/install/bin && ls -lAh ~/MultiMC/install/MultiMC
