if: tag IS NOT present
os: windows
language: cpp

install:
  - choco install openssl -y --x86
  - choco install jdk8 -y
  - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
  - choco install msys2 -y

script:
  - mkdir ~/MultiMC && cd ~/MultiMC
  - mkdir build
  - mkdir install
  - git clone --recursive https://github.com/Sebastian-byte/MultiMC5-Cracked.git src
  - cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=.\install
  - mingw32-make -j3
  - mingw32-make install
  - ls -lAh ~/MultiMC/ && ls -lAh ~/MultiMC/build && ls -lAh ~/MultiMC/install && ls -lAh ~/MultiMC/src && ls -lAh ~/MultiMC/install/bin && ls -lAh ~/MultiMC/install/MultiMC
