name: CI

env:
  QT_VERSION:     "5.12.7"
  MINGW_VERSION:  "win32_mingw73"
  MINGW_PATH:     "mingw73_32"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Install correct version of mingw
        run: |
          choco uninstall mingw --force
          choco uninstall strawberryperl --force
      - uses: numworks/setup-msys2@v1
        with:
          msystem: MINGW32

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          arch:    ${{ env.MINGW_VERSION }}
          extra:   --external 7z
          dir: ${{ github.workspace }}/

      #- uses: actions/checkout@v2

      - name: Compile
        run: |
          cd $HOME
          git clone --recursive https://github.com/Panderine/MultiMC5-Cracked.git MMC5C
          cd $HOME\MMC5C
          mkdir build
          
          cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=$HOME\MMC5C\build
          $GITHUB_WORKSPACE\Qt\$env.QT_VERSION\$env.MINGW_VERSION\bin\mingw32-make.exe -j3
          $GITHUB_WORKSPACE\Qt\$env.QT_VERSION\$env.MINGW_VERSION\bin\mingw32-make.exe install

      - name: Deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name: MultiMC
          path: $HOME\MMC5C\build
